// Builds the world from the club list: validates sources/clubs-hdf.csv, then writes
//   src/generated/clubs.ts        (the clubs, for the app)
//   ../../supabase/seed/10_universe.sql   (the same world, for the database)
// Run: pnpm --filter @legendes/data build:seed
// `--check` writes nothing and fails if the committed files are not what the club list produces
// (part of `pnpm test`, so CI catches a hand-edited CSV whose generated files were not rebuilt).
import { readFileSync, writeFileSync } from 'node:fs';
import { buildUniverse, parseClubs } from '../src/universe.ts';
import { universeSql } from '../src/sql.ts';

const csv = readFileSync(new URL('../sources/clubs-hdf.csv', import.meta.url), 'utf8');
const clubs = parseClubs(csv).sort((a, b) => a.id.localeCompare(b.id));
const universe = buildUniverse(clubs);

const generated = `// Generated by \`pnpm --filter @legendes/data build:seed\` from sources/clubs-hdf.csv. Do not edit.
import type { Club } from '../schema.ts';

export const CLUBS: readonly Club[] = ${JSON.stringify(clubs, null, 2)};
`;
const sql = universeSql(universe);
const targets = [
  { url: new URL('../src/generated/clubs.ts', import.meta.url), content: generated },
  { url: new URL('../../../supabase/seed/10_universe.sql', import.meta.url), content: sql },
];

if (process.argv.includes('--check')) {
  // Formatting is Prettier's business: compare what the script writes, before formatting, only
  // through the club data and the SQL, which Prettier leaves alone.
  const stale = targets.filter(
    ({ url, content }) => normalise(readFileSync(url, 'utf8')) !== normalise(content),
  );
  if (stale.length > 0) {
    console.error(
      `Out of date: ${stale.map((t) => t.url.pathname).join(', ')}. Run: pnpm --filter @legendes/data build:seed`,
    );
    process.exit(1);
  }
  console.log(`Generated world files are current (${clubs.length} clubs).`);
} else {
  for (const { url, content } of targets) writeFileSync(url, content);
  console.log(
    `World built: ${universe.leagues.length} league, ${universe.districts.length} districts, ` +
      `${universe.divisions.length} divisions, ${clubs.length} clubs.`,
  );
}

/** Whitespace, commas, quotes and semicolons are Prettier's: compare the content without them. */
function normalise(text: string): string {
  return text.replace(/[\s,"'`;]+/g, '');
}
