// Every card of the pilot as a plain row (id, class, rating, club, position), for the database:
// it checks that a card exists before a player can own it. The card itself is never stored: it is
// recomputed from its id (`findCard`), so the database holds references only.

import { cardClassOf, type CardClass } from './packs.ts';
import { insert, q } from './sql.ts';
import { cardOf, cardVariantsOf, type CardVariant } from './squad/cards.ts';
import { generateSquad } from './squad/generate.ts';
import { WORLD } from './world.ts';

export interface CardDef {
  readonly id: string;
  readonly playerId: string;
  readonly variant: CardVariant;
  readonly cardClass: CardClass;
  readonly rating: number;
  readonly clubId: string;
  readonly position: string;
}

/** The base card and the promo cards of every generated player, sorted by id. */
export function allCardDefs(): CardDef[] {
  const defs: CardDef[] = [];
  for (const club of WORLD.clubs) {
    for (const player of generateSquad(club).players) {
      for (const variant of cardVariantsOf(player)) {
        const card = cardOf(player, variant);
        defs.push({
          id: card.id,
          playerId: player.id,
          variant,
          cardClass: cardClassOf(card),
          rating: card.player.rating,
          clubId: club.id,
          position: card.player.positions[0] ?? 'CM',
        });
      }
    }
  }
  return defs.sort((a, b) => a.id.localeCompare(b.id));
}

const CHUNK = 500;
const COLUMNS = ['id', 'player_id', 'variant', 'class', 'rating', 'club_id', 'position'] as const;

/** The seed `supabase/seed/20_cards.sql`: idempotent upserts, a few hundred rows per statement. */
export function cardDefsSql(defs: readonly CardDef[]): string {
  const statements: string[] = [];
  for (let i = 0; i < defs.length; i += CHUNK) {
    statements.push(
      insert(
        'card_defs',
        COLUMNS,
        defs
          .slice(i, i + CHUNK)
          .map((d) => [
            q(d.id),
            q(d.playerId),
            q(d.variant),
            q(d.cardClass),
            String(d.rating),
            q(d.clubId),
            q(d.position),
          ]),
        'id',
      ),
    );
  }
  return `-- Generated by \`pnpm --filter @legendes/data build:cards\`. Do not edit.\n${statements.join('\n')}`;
}
