// The world as a seed script for Supabase (`supabase/seed/10_universe.sql`): idempotent upserts,
// so `pnpm db:reset` and a re-run on a live database give the same rows.

import { SEASON, type Club } from './schema.ts';
import type { Universe } from './universe.ts';

export const q = (value: string): string => `'${value.replace(/'/g, "''")}'`;
const n = (value: number | null): string => (value === null ? 'null' : String(value));

export function insert(
  table: string,
  columns: readonly string[],
  rows: readonly string[][],
  key: string,
): string {
  if (rows.length === 0) return '';
  const updates = columns
    .filter((c) => !key.split(', ').includes(c))
    .map((c) => `${c} = excluded.${c}`)
    .join(', ');
  const values = rows.map((r) => `  (${r.join(', ')})`).join(',\n');
  return `insert into public.${table} (${columns.join(', ')}) values\n${values}\non conflict (${key}) do${
    updates ? ` update set ${updates}` : ' nothing'
  };\n`;
}

function clubRow(c: Club): string[] {
  return [
    q(c.id),
    q(c.name),
    q(c.shortName),
    q(c.city),
    q(c.insee),
    q(c.districtId),
    q(c.divisionId),
    c.divisionKnown ? 'true' : 'false',
    q(c.colours.primary),
    q(c.colours.secondary),
    c.colours.tertiary === null ? 'null' : q(c.colours.tertiary),
    q(c.coloursSource),
    q(c.pattern),
    q(c.stadium.name),
    q(c.stadium.surface),
    n(c.founded),
    c.verified ? 'true' : 'false',
  ];
}

export function universeSql(universe: Universe): string {
  const parts = [
    '-- Generated by `pnpm --filter @legendes/data build:seed` from sources/clubs-hdf.csv. Do not edit.',
    insert(
      'leagues',
      ['id', 'name', 'region'],
      universe.leagues.map((l) => [q(l.id), q(l.name), q(l.region)]),
      'id',
    ),
    insert(
      'districts',
      ['id', 'league_id', 'name', 'departments'],
      universe.districts.map((d) => [
        q(d.id),
        q(d.leagueId),
        q(d.name),
        `array[${d.departments.map(q).join(', ')}]`,
      ]),
      'id',
    ),
    insert(
      'divisions',
      ['id', 'scope', 'level', 'rank', 'name', 'league_id', 'district_id', 'pool'],
      universe.divisions.map((d) => [
        q(d.id),
        q(d.scope),
        q(d.level),
        n(d.rank),
        q(d.name),
        d.leagueId === null ? 'null' : q(d.leagueId),
        d.districtId === null ? 'null' : q(d.districtId),
        d.pool === null ? 'null' : q(d.pool),
      ]),
      'id',
    ),
    insert(
      'clubs',
      [
        'id',
        'name',
        'short_name',
        'city',
        'insee',
        'district_id',
        'division_id',
        'division_known',
        'primary_colour',
        'secondary_colour',
        'tertiary_colour',
        'colours_source',
        'pattern',
        'stadium_name',
        'surface',
        'founded',
        'verified',
      ],
      universe.clubs.map(clubRow),
      'id',
    ),
    insert(
      'club_seasons',
      ['club_id', 'season', 'division_id'],
      universe.clubs.map((c) => [q(c.id), q(SEASON), q(c.divisionId)]),
      'club_id, season',
    ),
  ];
  return parts.filter(Boolean).join('\n');
}
