-- Generated by `pnpm --filter @legendes/data build:seed` from sources/clubs-hdf.csv. Do not edit.
insert into public.leagues (id, name, region) values
  ('hauts-de-france', 'Ligue de Football des Hauts-de-France', 'Hauts-de-France')
on conflict (id) do update set name = excluded.name, region = excluded.region;

insert into public.districts (id, league_id, name, departments) values
  ('aisne', 'hauts-de-france', 'District de l''Aisne', array['02']),
  ('artois', 'hauts-de-france', 'District de l''Artois', array['62']),
  ('cote-d-opale', 'hauts-de-france', 'District de la Côte d''Opale', array['62']),
  ('escaut', 'hauts-de-france', 'District de l''Escaut', array['59']),
  ('flandres', 'hauts-de-france', 'District des Flandres', array['59']),
  ('oise', 'hauts-de-france', 'District de l''Oise', array['60']),
  ('somme', 'hauts-de-france', 'District de la Somme', array['80'])
on conflict (id) do update set league_id = excluded.league_id, name = excluded.name, departments = excluded.departments;

insert into public.divisions (id, scope, level, rank, name, league_id, district_id, pool) values
  ('n2-a', 'national', 'national', 2, 'National 2 groupe A', null, null, 'A'),
  ('n2-b', 'national', 'national', 2, 'National 2 groupe B', null, null, 'B'),
  ('n2-c', 'national', 'national', 2, 'National 2 groupe C', null, null, 'C'),
  ('n2-d', 'national', 'national', 2, 'National 2 groupe D', null, null, 'D'),
  ('n3-hdf', 'national', 'national', 3, 'National 3 Hauts-de-France', null, null, 'HDF'),
  ('hdf-r1', 'league', 'regional', 1, 'Régional 1 Hauts-de-France', 'hauts-de-france', null, null),
  ('hdf-r2', 'league', 'regional', 2, 'Régional 2 Hauts-de-France', 'hauts-de-france', null, null),
  ('hdf-r3', 'league', 'regional', 3, 'Régional 3 Hauts-de-France', 'hauts-de-france', null, null),
  ('escaut-d1', 'district', 'district', 1, 'District de l''Escaut D1', null, 'escaut', null),
  ('escaut-d2', 'district', 'district', 2, 'District de l''Escaut D2', null, 'escaut', null),
  ('escaut-d3', 'district', 'district', 3, 'District de l''Escaut D3', null, 'escaut', null),
  ('escaut-d4', 'district', 'district', 4, 'District de l''Escaut D4', null, 'escaut', null),
  ('escaut-d5', 'district', 'district', 5, 'District de l''Escaut D5', null, 'escaut', null),
  ('escaut-d6', 'district', 'district', 6, 'District de l''Escaut D6', null, 'escaut', null)
on conflict (id) do update set scope = excluded.scope, level = excluded.level, rank = excluded.rank, name = excluded.name, league_id = excluded.league_id, district_id = excluded.district_id, pool = excluded.pool;
