// Regenerates src/selftest/golden.ts from the current engine. Run on purpose only:
//   pnpm determinism:update
import { writeFileSync } from 'node:fs';
import { runDeterminismScenario } from '../src/selftest/index.ts';

const report = runDeterminismScenario();
const target = new URL('../src/selftest/golden.ts', import.meta.url);

writeFileSync(
  target,
  `// Reference fingerprint of the determinism scenario. Generated by \`pnpm determinism:update\`.
// Only regenerate on purpose (a change here means replays/validations of older matches break).
export const DETERMINISM_GOLDEN = {
  digest: '${report.digest}',
  words: ${report.words},
} as const;
`,
);
console.log(`Determinism golden updated: ${report.digest} (${report.words} words)`);
