// Reference fingerprint of the determinism scenario. Generated by `pnpm determinism:update`.
// Only regenerate on purpose (a change here means replays/validations of older matches break).
export const DETERMINISM_GOLDEN = {
  digest: '2413c25a7039b48f',
  words: 240176,
} as const;
