// Reference fingerprint of the determinism scenario. Generated by `pnpm determinism:update`.
// Only regenerate on purpose (a change here means replays/validations of older matches break).
export const DETERMINISM_GOLDEN = {
  digest: '0b9e2542b487b080',
  words: 187046,
} as const;
