// Reference fingerprint of the determinism scenario. Generated by `pnpm determinism:update`.
// Only regenerate on purpose (a change here means replays/validations of older matches break).
export const DETERMINISM_GOLDEN = {
  digest: 'dd21b3de96cb587e',
  words: 241938,
} as const;
