-- Légendes du Dimanche — the world (Phase 3): leagues, districts, divisions, clubs.
-- Public reference data: everyone can read it, nobody writes it from a client. The seed
-- (supabase/seed/10_universe.sql, generated by `pnpm --filter @legendes/data build:seed`) fills it.

create table public.leagues (
  id text primary key check (id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  name text not null,
  region text not null
);

create table public.districts (
  id text primary key check (id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  league_id text not null references public.leagues (id),
  name text not null,
  departments text[] not null check (cardinality(departments) > 0)
);
create index districts_league_idx on public.districts (league_id);

-- Depth varies from one district to another: a division is (level, rank) inside a scope.
create table public.divisions (
  id text primary key check (id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  scope text not null check (scope in ('national', 'league', 'district')),
  level text not null check (level in ('national', 'regional', 'district')),
  rank smallint not null check (rank between 1 and 9),
  name text not null,
  league_id text references public.leagues (id),
  district_id text references public.districts (id),
  pool text,
  check ((scope = 'district') = (district_id is not null))
);
create index divisions_district_idx on public.divisions (district_id);

create table public.clubs (
  id text primary key check (id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  name text not null,
  short_name text not null,
  city text not null,
  insee text not null check (insee ~ '^\d[0-9AB]\d{3}$'),
  district_id text not null references public.districts (id),
  division_id text not null references public.divisions (id),
  primary_colour text not null check (primary_colour ~ '^#[0-9a-f]{6}$'),
  secondary_colour text not null check (secondary_colour ~ '^#[0-9a-f]{6}$'),
  tertiary_colour text check (tertiary_colour ~ '^#[0-9a-f]{6}$'),
  colours_source text not null check (colours_source in ('known', 'guess')),
  pattern text not null check (pattern in ('plain', 'stripes', 'hoops', 'sash', 'checks')),
  stadium_name text not null,
  surface text not null check (surface in ('grass', 'artificial', 'stabilized')),
  founded smallint check (founded between 1850 and 2026),
  verified boolean not null default false
);
create index clubs_district_idx on public.clubs (district_id);
create index clubs_division_idx on public.clubs (division_id);

-- The division of each club's first team, season by season (promotions and relegations later).
create table public.club_seasons (
  club_id text not null references public.clubs (id),
  season text not null check (season ~ '^\d{4}-\d{2}$'),
  division_id text not null references public.divisions (id),
  primary key (club_id, season)
);

alter table public.leagues enable row level security;
alter table public.districts enable row level security;
alter table public.divisions enable row level security;
alter table public.clubs enable row level security;
alter table public.club_seasons enable row level security;

create policy "the world is public" on public.leagues for select to anon, authenticated using (true);
create policy "the world is public" on public.districts for select to anon, authenticated using (true);
create policy "the world is public" on public.divisions for select to anon, authenticated using (true);
create policy "the world is public" on public.clubs for select to anon, authenticated using (true);
create policy "the world is public" on public.club_seasons for select to anon, authenticated using (true);
